### ISSUE TITLE
Code Review: ApeToken

### ISSUE THREAD

**Issue by storming0x** [coordinape/coordinape-protocol#15]
scope: 
- ApeToken.sol
- TokenAccessControl.sol

**Comment by storming0x** [comment]
Small comment:

In yearn vaults we add this check

https://github.com/yearn/yearn-vaults/blob/2a28331438063a48684db4143ad293821671cc67/contracts/Vault.vy#L756

it ensures owner cant be zero, which is not a problem since ECDSA also checks signer is never zero in this version, but is good to make the check explicit in any case.

https://github.com/coordinape/coordinape-protocol/blob/df88ddd07d99429d10c7577da639ff38ff6a1d2e/contracts/ApeProtocol/token/ApeToken.sol#L42

**Comment by storming0x** [comment]
Small Suggestion:

I did not see in 4.0.0-rc that the OZ contracts checks for transfers to address 0x0, is this something we want to require as check on both transfers?

https://github.com/coordinape/coordinape-protocol/blob/df88ddd07d99429d10c7577da639ff38ff6a1d2e/contracts/ApeProtocol/token/ApeToken.sol#L59

**Comment by storming0x** [comment]
Small gas optimization?

https://github.com/coordinape/coordinape-protocol/blob/df88ddd07d99429d10c7577da639ff38ff6a1d2e/contracts/ApeProtocol/token/TokenAccessControl.sol#L21

putting the "!whitelistDisabled" check short circuits the check faster if the flag is turn on at some point without reading the whitelist address storage

**Comment by storming0x** [comment]
Question:

Not an issue per se,  guessing the requirement for whitelist is for freezing funds of specific accounts? usually these access controls are also paired with upgradability, since the requirement here is to just freeze funds but not able to recover them at any point in time, or am i misunderstanding the design?

https://github.com/coordinape/coordinape-protocol/blob/df88ddd07d99429d10c7577da639ff38ff6a1d2e/contracts/ApeProtocol/token/TokenAccessControl.sol#L21

**Comment by storming0x** [comment]
Small comment:

Here the modifier the normal flow for token transfers is that the contract is not paused right?

https://github.com/coordinape/coordinape-protocol/blob/df88ddd07d99429d10c7577da639ff38ff6a1d2e/contracts/ApeProtocol/token/TokenAccessControl.sol#L20

Maybe a bit nitpicky, but usually modifiers state what is the condition for the scope of the method to go forward,
so here maybe `isNotPaused`  or `notPaused` may be better to read.

**Comment by storming0x** [comment]
Mostly small, nitpicks. Most of the code in the scope LGTM!

**Comment by cesarsld** [comment]
> Question:
> 
> Not an issue per se, guessing the requirement for whitelist is for freezing funds of specific accounts? usually these access controls are also paired with upgradability, since the requirement here is to just freeze funds but not able to recover them at any point in time, or am i misunderstanding the design?
> 
> https://github.com/coordinape/coordinape-protocol/blob/df88ddd07d99429d10c7577da639ff38ff6a1d2e/contracts/ApeProtocol/token/TokenAccessControl.sol#L21

Design is to enable a whitelisted member to transfer tokens while the transfer feature is paused

**Comment by cesarsld** [comment]
> Small Suggestion:
> 
> I did not see in 4.0.0-rc that the OZ contracts checks for transfers to address 0x0, is this something we want to require as check on both transfers to avoid holders accidentally burning shares?
> 
> https://github.com/coordinape/coordinape-protocol/blob/df88ddd07d99429d10c7577da639ff38ff6a1d2e/contracts/ApeProtocol/token/ApeToken.sol#L59

Unless I looked in the wrong place, OZ does revert if recipient is 0x0
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/1ee939e7c4b2c1fe84e6f5b6a7c1ce5e7d91667f/contracts/token/ERC20/ERC20.sol#L212

**Comment by cesarsld** [comment]
Thank you @storming0x 
I will implement changes on your feedback!

**Comment by parseb** [comment]
I think @cesarsld is on point. 🤔 
Line 60:
`        return ERC20.transfer(_to, _amount);`
explicit **ERC20.** transfer uses **_transfer()** function which **validates input not being default 0x0** address.  
        _transfer(_msgSender(), recipient, amount);_
Condition checked by ERC20 line 211:
`        require(sender != address(0), "ERC20: transfer from the zero address");`

**Comment by storming0x** [comment]
Im good to close issue based on comments and discussions @cesarsld

**Comment by spydermonkee** [comment]
Thanks a lot, @storming0x for your review. Nice to meet you through this avenue, BTW :)

I'm ready to close this issue and we're basically ready for deploying the token contracts. There are only 4 commits since your last comment and they seem innocuous enough to me:  https://github.com/coordinape/coordinape-protocol/commits/main/contracts/ApeProtocol/token

Do you have any last concerns about any of these new commits before we deploy this?
thanks!

**Comment by storming0x** [comment]
> https://github.com/coordinape/coordinape-protocol/commits/main/contracts/ApeProtocol/token

i saw the latest commits, dont see any security issue at first glance in latest changes.

**Comment by spydermonkee** [comment]
Thanks a lot, @storming0x!
