### ISSUE TITLE
allow `setAllowance` to accept `_intervalStart` argument in the past

### ISSUE THREAD

**Issue by levity** [coordinape/coordinape-protocol#26]
it would be for a situation where the circle has a repeating epoch, the epoch has already started, and the allowance hasn't been set yet. 

you would want to set _intervalStart to match the epoch's (past) start time, and the cooldownInterval to match the epoch's repeating period, so that for the next epoch, the allowance resets at the right time.

**Comment by spydermonkee** [comment]
I'm also curious to discuss any possible negative or security implications of this change that we may not see at first, @cesarsld
